apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

replicas:
- name: vote
  count: 7

configMapGenerator:
- name: vote-literals
  literals:
  - OPTION_A=STAGING
  - OPTION_B=DEV
