apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vote
    tier: front
  name: vote
spec:
  replicas: 4
  template:
    spec:
      containers:
      - image: schoolofdevops/vote:v4
        name: vote
