apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base

replicas:
- name: vote
  count: 2

images:
- name: schoolofdevops/vote
  newTag: v4 # {"$imagepolicy": "flux-system:vote:tag"}

configMapGenerator:
- name: vote-config
  literals:
  - OPTION_A=ADIDAS
  - OPTION_B=NIKE
